### ISSUE TITLE
Raw identifiers break the parsing completely

### ISSUE THREAD

**Issue by MoritzKn** [tree-sitter/tree-sitter-rust#101]
Rust has so called [Raw identifiers](https://doc.rust-lang.org/edition-guide/rust-2018/module-system/raw-identifiers.html#raw-identifiers).

They look like this:

```rust
let r#let = 12;
println!("the var let ()", r#let);
```

This breaks the parsing completely for me.

<img width="617" alt="Screenshot 2021-01-13 at 21 53 47" src="https://user-images.githubusercontent.com/10676525/104509331-d1c4ab00-55e9-11eb-946d-2a69f21dc530.png">

**Comment by maxbrunsfeld** [comment]
This has been fixed for quite a while. A while ago, Atom was upgraded to use a recent `tree-sitter-rust` with the fix. I'm not sure what their release schedule is though.

**Comment by MoritzKn** [comment]
Ahhh okay, my bad for not verifying this properly, sorry.

**Comment by maxbrunsfeld** [comment]
No problem!
