### ISSUE TITLE
Consecutive `super`s dont get considered as keyword

### ISSUE THREAD

**Issue by crowlKats** [tree-sitter/tree-sitter-rust#114]
In the scenario of `super::super`, only the first super is considered a keyword, whereas the second one isnt considered as anything

**Comment by nickeb96** [comment]
This is still an issue a year later.  Any word on fixing this?

**Comment by aryx** [comment]
What does super::super mean?
super is a keyword when you try to access the fields from the parent class I guess. What does super::super mean? the parent class of the parent class?

**Comment by dtolnay** [comment]
```rust
mod a {
    fn x() {
        println!("huh");
    }

    pub mod b {
        pub mod c {
            pub fn y() {
                super::super::x();
            }
        }
    }
}

fn main() {
    a::b::c::y();
}
```

**Comment by dtolnay** [comment]
![Screenshot from 2022-07-29 03-20-23](https://user-images.githubusercontent.com/1940490/181739035-d56fb7cf-946c-4a42-85f3-c256e32db83e.png)

**Comment by nickeb96** [comment]
> What does super::super mean? super is a keyword when you try to access the fields from the parent class I guess. What does super::super mean? the parent class of the parent class?

@aryx that is not at all what the super keyword does.  Rust does not have classes or inheritance.  It also does not have constructors at the language level in the same way Java and C++ does.

The super keyword is for accessing a parent module relative to the current module.  `super::super` is completely valid.
