### ISSUE TITLE
let patterns/identifier arent considered

### ISSUE THREAD

**Issue by crowlKats** [tree-sitter/tree-sitter-rust#117]
in the example `let x = 0;`, `x` isnt considered anything. same would be for any usages of `x`. these should be considered.

I am not sure if this is an issue with tree-sitter-rust, me missing a specific highlight name, or tree-sitter-highlighter (as goes for all my other opened issues, so apologies if they are in the wrong place), as i am just encountering these problems through the usage of tree-sitter-highlighter with tree-sitter-rust

**Comment by MinusGix** [comment]
Were you able to get this resolved? I've ran into the same issue currently.

**Comment by ebkalderon** [comment]
I can't reproduce this on the latest version of `tree-sitter-rust`. Writing `let x = 0;` into an open `rust` buffer, moving the cursor over the `x`, and then running `:TSHighlightCapturesUnderCursor` produces the output:

```
# Treesitter
* @variable
```

Doing the same over the `x` in `x = 0;` produces the same output. Perhaps this issue can be closed?
