### ISSUE TITLE
Don't discard non-special tokens in macro invocations

### ISSUE THREAD

**Issue by Wilfred** [tree-sitter/tree-sitter-rust#119]
```
vec![Foo::bar()];
baz![?];
```

The `::` and `?` are not included in the syntax tree. I think this is because `_non_special_token` is matching these with a regular expression, unlike e.g. `as`.

https://github.com/tree-sitter/tree-sitter-rust/blob/cc7bdd3e6d14677e8aa77da64f6a3f57b6f8b00a/grammar.js#L193-L198

This is causing issues for [difftastic](https://github.com/wilfred/difftastic), where `Foo::bar()` preserves the `::` but `vec![Foo::bar()]` does not.

**Comment by Wilfred** [comment]
Related: https://github.com/tree-sitter/tree-sitter/issues/1151

**Comment by amaanq** [comment]
I'm hoping this is fixed on master, try it out!

But a good idea might be to just inject Rust inside a macro's token tree
