### ISSUE TITLE
Support for format_args_capture feature

### ISSUE THREAD

**Issue by rod-stuchi** [tree-sitter/tree-sitter-rust#129]
The [format_args_capture](https://rust-lang.github.io/rfcs/2795-format-args-implicit-identifiers.html) was stabilized in [1.58.0](https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html#captured-identifiers-in-format-strings). 

It would be nice to resolve the captured identifiers.

**Comment by nik-rev** [comment]
I made a separate tree-sitter grammar for Rust's string interpolation macros that use `format_args!`.

Grammar: https://github.com/nik-rev/tree-sitter-rust-format-args/tree/main
It is used in Helix: https://github.com/helix-editor/helix/commit/1023e8f96482f725465bf2bc059e274f6ac0bb26

Example with syntax highlighting: 

![image](https://github.com/user-attachments/assets/6c234aa6-fbda-4209-908e-ab67566e4fd5)
