### ISSUE TITLE
Support try blocks

### ISSUE THREAD

**Issue by LordMZTE** [tree-sitter/tree-sitter-rust#133]
The nightly version of rust supports try blocks, with this sort of syntax:
```rust
let n = try {
    do_stuff();
    5
};
```
It is pretty much the same as unsafe blocks syntax-wise.

Using tree-sitter-rust with tree-sitter.nvim, the syntax highlighting for the code above is pretty messed up, as tree-sitter-rust doesn't understand this syntax yet.

**Comment by amaanq** [comment]
That's behind an unstable feature, no point adding that now.

**Comment by ahlinc** [comment]
For the try blocks it would be awesome to make an exception and support them.
@amaanq  Also it would be good to use rust-analyzer as an orient of what to support in this parser too.

**Comment by amaanq** [comment]
I've added support for it now, I agree adding commonly-used unstable features is nice to support (e.g. disabling auto traits, generators, try blocks, etc)
