### ISSUE TITLE
Some code is not highlighted correctly

### ISSUE THREAD

**Issue by jorendorff** [tree-sitter/tree-sitter-rust#149]
[Some folks noticed](https://twitter.com/mycoliza/status/1549063442333462529) that GitHub's code highlighting for Rust recently regressed. Some examples are

- not highlighting `async` as a keyword in

    ```rust
    pub async fn foo() {}
    ```

- highlighting the two match arms differently in 

    ```rust
    impl Lower {
        pub fn lower(&self, stmt: &Stmt) {
            match &stmt.node {
                RawStmt::Read(e) => self.lower_read(e),
                RawStmt::Print { expr, kind, newline, } => self.lower_print(expr, *kind, *newline),
            }
        }
    }
    ```

The cause of the regression is that GitHub recently switched from Linguist to `tree-sitter-rust` for Rust code highlighting.

The first bug is a one-liner in [queries/highlights.scm](https://github.com/tree-sitter/tree-sitter-rust/blob/master/queries/highlights.scm#L83). The second bug is more complicated. Part of it is due to handling `(identifier)` and `(scoped_identifier)` but not `(type_identifier)` and `(scoped_type_identifier)`, but after that, it's probably impossible to distinguish names of struct-like enum variants from names of structs in `(struct_pattern)` using this pattern language. So whether we highlight them as enum variants (which would be correct in this example) or as type names, we'll be wrong sometimes.

**Comment by aDotInTheVoid** [comment]
For future reference, here's what these look like now:

![The first example from the above text, with async not hilighed](https://user-images.githubusercontent.com/28781354/179622816-9029ae3c-ab0d-46e9-b3be-992e81e31620.png)
![The second exaple, with both match arms hilighed differently](https://user-images.githubusercontent.com/28781354/179622852-fbf681f8-1685-446d-9994-6ff5fe69cf1f.png)
