### ISSUE TITLE
Incorrect Highlighting for tuple parameter names

### ISSUE THREAD

**Issue by Nokel81** [tree-sitter/tree-sitter-rust#15]
![image](https://user-images.githubusercontent.com/8225332/52892130-d3676900-315d-11e9-9c29-35db171b1c4f.png)

**Comment by maxbrunsfeld** [comment]
Fixed via https://github.com/tree-sitter/tree-sitter-rust/commit/0a9f2c844a42463c58da436bce8ab7fe8cef7d0e.
