### ISSUE TITLE
Add support for `if-let chain`

### ISSUE THREAD

**Issue by faptc** [tree-sitter/tree-sitter-rust#161]
if-let chain will soon be stable. Tracking issue for the feature: https://github.com/rust-lang/rust/issues/53667

The syntax is not highlighted correctly for the `let` keyword.

I have this code:
```rust
fn foo(b: bool, x: Option<u32>) {
    if b && let Some(x) = x {}
}
```

I expect the let keyword be highlighted.

Instead, let is not highlighted:
![image](https://user-images.githubusercontent.com/94724914/198826892-5e075e93-aa53-4fca-a460-6ada4ec69456.png)

**Comment by AndyJado** [comment]
perhaps `let-else` as well?

**Comment by solidiquis** [comment]
Yeah `let-else` and `if-let` chain would be nice.

<img width="512" alt="Screen Shot 2023-04-13 at 1 13 05 PM" src="https://user-images.githubusercontent.com/45523555/231873731-72dabefc-28f9-4872-9178-66b37fb39619.png">
