### ISSUE TITLE
Incorrect syntax highlighting: the color using the glob-like brace syntax 

### ISSUE THREAD

**Issue by silentsokolov** [tree-sitter/tree-sitter-rust#17]
![1558701767076](https://user-images.githubusercontent.com/398939/58328461-cf24a900-7e3a-11e9-9afa-54e9dcbc4770.jpg)

**Expected behavior**: the color of the name must be same for any kind of `use`

**Versions**
```
atom --version                                                                                                                                                        master
Atom    : 1.37.0
Electron: 2.0.18
Chrome  : 61.0.316
```

**Comment by GrayJack** [comment]
Sorry, I think this is the wrong place for your problem, who chooses what token becomes what class is the atom package `language-rust-bundled`

If you like, you can try my personal atom rust language plugin, it's called `language-rust-treesitter`, install from git, I just pushed a fix that uses my fix of this repo to make it more complete

**Comment by maxbrunsfeld** [comment]
I believe this is fixed by https://github.com/tree-sitter/tree-sitter-rust/pull/30.
