### ISSUE TITLE
Should the path seperator (`::`) be considered as an `@operator` instead of `@punctuation.delimiter`?

### ISSUE THREAD

**Issue by ChrisMGeo** [tree-sitter/tree-sitter-rust#171]
Similar to how textmate grammars do it, should the path seperator for crates, modules, etc. be considered as `@operator` instead of `@punctuation.delimiter`?

**Comment by nickeb96** [comment]
Definitely not. `::` is a path delimiter, not an operator.

Most people wouldn't consider `/` in a file path to be an operator either.  That's essentially what `::` is.
