### ISSUE TITLE
Differentiate `//` from `///`

### ISSUE THREAD

**Issue by WhyNotHugo** [tree-sitter/tree-sitter-rust#175]
Currently lines starting with `//` and `///`  both map to `line_comment`.

This makes it impossible to highlight both of them with different style. Specifically, lines starting with `///` (and `//!`) are `rustdoc`, and get different treatment (they end up in generated documentation).

In particular, I'd like to highlight them both with different style since it's current very easy to confuse the two, especially when they're in consecutive lines.

**Comment by amaanq** [comment]
Use match predicates to check the beginning

**Comment by Chris00** [comment]
This will be [done in Emacs](https://lists.gnu.org/archive/html/emacs-devel/2023-11/msg01350.html).

**Comment by clason** [comment]
Closed by #195
