### ISSUE TITLE
Can you add support for wasm?

### ISSUE THREAD

**Issue by Yuzuchi** [tree-sitter/tree-sitter-rust#176]
Can you add support for wasm? I was programming in rust and all the wasm part was showing me as an error.

**Comment by bew** [comment]
What does the wasm part look like?
Know that Rust is not the only language which be compiled to wasm. Other languages might want this as well.

You should find a dedicated tree sitter for wasm, and tweak language injection queries in your tool/editor to recognize wasm-in-rust-code as wasm language (to use the wasm parser)

**Comment by Yuzuchi** [comment]
ty
