### ISSUE TITLE
Inconsistent syntax highlighting for function arguments

### ISSUE THREAD

**Issue by florianbsh** [tree-sitter/tree-sitter-rust#179]
Hi,

There is an inconsistency in function arguments syntax highlighting. In the code below, I would expect `f` in the `write!` macro to have the same formatting as the `f` in the function arguments. I am using Helix 23.05 but this seemed to be a tree-sitter-related issue.

![image](https://github.com/tree-sitter/tree-sitter-rust/assets/46905046/bb9c5737-7da5-4093-8a1d-c51edf1de9aa)

**Comment by amaanq** [comment]
Not a tree-sitter issue, you're looking for semantic tokens support

**Comment by florianbsh** [comment]
Oh okay, so that's rather an editor issue (Helix in this case)?

**Comment by amaanq** [comment]
well, in a sense yes, but really i'd think it's the lsp (rust analyzer), I'm assuming helix properly highlights parameter semantic tokens
