### ISSUE TITLE
Highlight `while` as `@keyword.rust`

### ISSUE THREAD

**Issue by SvenFibelkorn** [tree-sitter/tree-sitter-rust#181]
Keywords like `pub`, `fn` and `for` get highlighted as keywords. `Inspect` in neovim shows `@keyword.rust links to Keyword rust`. Keywords like `while` and `loop`, `break` and `continue`, `if` and `else` however do not show `@keyword.rust`.

Some themes italicize `@keyword.rust` and having `for` italicized but not `while` presents a minor visual inconsistency.

**Comment by amaanq** [comment]
This is (likely?) an nvim-treesitter issue not an issue w/ tree-sitter-rust, and even then it's hard to discern the issue... all the ones you mentioned not showing `@keyword.rust` either are `@conditional` or `@repeat`
