### ISSUE TITLE
Attribute doesn't parse correctly

### ISSUE THREAD

**Issue by cloudhead** [tree-sitter/tree-sitter-rust#193]
The "attribute" highlight group only parses the `#[` and not the rest, eg. here it is highlighted in blue:

<img width="323" alt="image" src="https://github.com/tree-sitter/tree-sitter-rust/assets/40774/7e2a6466-6c88-4dab-9095-a46603a391f7">

**Comment by amaanq** [comment]
not a parse error, whatever highlights you have in the tool you use must be configured with the queries it uses

**Comment by cloudhead** [comment]
Ok, I'm using this library; is there a complete list of highlight groups somewhere? I find it strange that the `attribute` group only highlights the first two characters.. is it because the code inside is a different language?

**Comment by amaanq** [comment]
Are you using the cli with `tree-sitter highlight`? If not, then whatever tool it is has the issue

**Comment by cloudhead** [comment]
I've figured it out, thanks and sorry for the noise. The problem was not understanding that tree-sitter will "nest" syntax groups.
