### ISSUE TITLE
Why does the nvim implementation differ so much?

### ISSUE THREAD

**Issue by tonijarjour** [tree-sitter/tree-sitter-rust#197]
Hello, I want to ask why the nvim-treesitter implementation differs so significantly from this one. You can compare the `highlights.scm` files in each case:
[nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter/blob/eb96ca52a7e72ec6d45b163e90bcb5e0774d44ad/queries/rust/highlights.scm)
[tree-sitter-rust](https://github.com/tree-sitter/tree-sitter-rust/blob/48e053397b587de97790b055a1097b7c8a4ef846/queries/highlights.scm)

Nvim's implementation is much more extensive. Here's a comparison image:
![image](https://github.com/tree-sitter/tree-sitter-rust/assets/39845673/e29aac48-5add-4009-9ddb-7e6625083f63)

**Comment by amaanq** [comment]
It's just preference, nvim's is more granular to allow for more user-control, tree-sitter's is more general and hits more important parts, you can PR relevant bits you'd like added of course if they make sense :)
