### ISSUE TITLE
Double cfg macro inside array isn't parsed correctly

### ISSUE THREAD

**Issue by ThomasFrans** [tree-sitter/tree-sitter-rust#199]
When you have something like the following, it isn't parsed correctly. The first cfg macro is highlighted the way normal ones are highlighted, but all the next ones in the array are incorrect.

```rust
fn foo() {
    [
        #[cfg(feature = "json")]
        "hi",
        #[cfg(feature = "yaml")]
        "bye",
    ];
}
```

![image](https://github.com/tree-sitter/tree-sitter-rust/assets/48214567/7a69e09e-a0de-47e6-a1ba-686e08db6db3)

**Comment by amaanq** [comment]
if it's an editor highlighting bug then this is the wrong repo and should be filed w the editor specific repo (neovim would be nvim-treesitter)

if the parse tree is incorrect post the code and tree

**Comment by ThomasFrans** [comment]
No, it's a parser issue. Here I recreated a minimal example with the `tree-sitter` cli tool.

### Tree-sitter parser output

![image](https://github.com/tree-sitter/tree-sitter-rust/assets/48214567/b89b2ac3-3392-47d7-80c8-fd72149c13fd)

### Code

```rust
fn main() {
    [
    #[cfg(linux)]
    "a",
    #[cfg(unix)]
    "b",
    ];
}
```

**Comment by amaanq** [comment]
thanks for the report, fixed now
