### ISSUE TITLE
Syntax is broken for some weird cases

### ISSUE THREAD

**Issue by juhaku** [tree-sitter/tree-sitter-rust#203]
The treesitter syntax has been broken for quite some time for some weird edgecases. E.g. here is a conditional functionality that should be enabled only when such feature is actually enabled. However this feature is not enabled and everything is correct with the code base but still the treesitter grammar adds the misleading undercurls to the code.
![image](https://github.com/tree-sitter/tree-sitter-rust/assets/26358664/2d703b98-eee1-4174-a25f-66f538e6daa7)

What it actually should look like is as follows:
![image](https://github.com/tree-sitter/tree-sitter-rust/assets/26358664/a301ca23-19e1-4c40-9008-215bd0ac79e9)

I'll post some more when I come across them

**Comment by amaanq** [comment]
That's LSP stuff, not tree-sitter
