### ISSUE TITLE
bug: Half-open ranges are not parsed correctly in match statements

### ISSUE THREAD

**Issue by AlexCid** [tree-sitter/tree-sitter-rust#205]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-rust

### Describe the bug

The Rust parser emits an error token for the following code:
```rust
match foo {
    1.. => {}
};
```
Right half-open inclusive ranges (such as ..=1) are also concerned.

### Steps To Reproduce/Bad Parse Tree

The code above is parsed to the following s-expression:

```
(source_file (expression_statement (match_expression value: (identifier) body: (match_block (match_arm pattern: (match_pattern (remaining_field_pattern)) (ERROR (integer_literal)) value: (block))))) (empty_statement))
```

### Expected Behavior/Parse Tree

The expected s-expression would be rather
```
(source_file (expression_statement (match_expression value: (identifier) body: (match_block (match_arm pattern: (match_pattern (range_expression (integer_literal))) ) value: (block))))) (empty_statement))
```
or something similar

### Repro

```Rust
match foo {
    1.. => {}
};
```

**Comment by amaanq** [comment]
Thanks, fixed on master
