### ISSUE TITLE
bug: Parser errors when macros are invoked with multiple arguments

### ISSUE THREAD

**Issue by ribru17** [tree-sitter/tree-sitter-rust#206]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-rust

### Describe the bug

When giving a macro multiple arguments (e.g. `println!("{}", "hello");`), the parser errors with something like:
```scheme
(expression_statement)
 (unit_expression)
  (ERROR)
```
Perhaps similar to #98

This is especially unfortunate when the inside of the macro contains a function call, as it will not be recognized as a function call and thus not selectable by a textobjects query.

### Steps To Reproduce/Bad Parse Tree

```scheme
(expression_statement) 
 (macro_invocation) 
  macro: (identifier) 
  (token_tree) 
   (expression_statement) 
    (unit_expression) 
     (ERROR) 
   (string_literal) 
   (identifier) 
   (token_tree) 
```

### Expected Behavior/Parse Tree

```scheme
(expression_statement) 
 (macro_invocation) 
  macro: (identifier) 
  (token_tree) 
   (string_literal) 
   (call_expression) 
    function: (identifier) 
    arguments: (arguments) 
```

### Repro

```Rust
println!("{}", returns_string_hello());
```

**Comment by amaanq** [comment]
That's not the output from tree-sitter's CLI

**Comment by ribru17** [comment]
I see, my apologies. Thanks for the information

**Comment by mkatychev** [comment]
@amaanq can you show the CLI input for your query? https://github.com/nvim-treesitter/nvim-treesitter/issues/5958#issuecomment-1905243017 this comment claims it's an issue with tree-sitter-rust
