### ISSUE TITLE
feature: Class Inheritance

### ISSUE THREAD

**Issue by F474M0R64N4** [tree-sitter/tree-sitter-rust#209]
### Did you check the tree-sitter docs?

- [x] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser

### Is your feature request related to a problem? Please describe.

As a developer using our software, I have come across a scenario where implementing class inheritance would significantly enhance the functionality of my project. Currently, the ability to model class inheritance is not supported in our system, which limits the flexibility and efficiency of the codebase.

In many object-oriented programming languages, class inheritance is a fundamental concept that allows one class to inherit the properties and methods of another class. This feature provides a clear structure for the code, promotes code reuse, and simplifies the development process.

Implementing class inheritance in our software will allow developers to create more complex and interconnected systems, thereby improving the overall quality and maintainability of the code. It will also enable developers to leverage existing code more effectively, leading to increased productivity.

I kindly request that you consider adding support for class inheritance in an upcoming update of our software. I believe that this feature will greatly benefit all users and significantly enhance the capabilities of our platform.

Thank you for considering this feature request. I am looking forward to hearing your thoughts and suggestions on how we can best implement this feature.

### Describe the solution you'd like

The solution I propose involves modifying the provided Rust code to work with the concept of "traits" instead of "inheritance" as it is in many other languages like Java or C++.

### Describe alternatives you've considered

...

**Comment by amaanq** [comment]
Uh this is not the rust-lang repo, this is just a tree-sitter grammar for parsing rust code.
