### ISSUE TITLE
feature: c string literals have been stabilized in 1.77

### ISSUE THREAD

**Issue by Ddystopia** [tree-sitter/tree-sitter-rust#210]
### Did you check the tree-sitter docs?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser

### Is your feature request related to a problem? Please describe.

[C string literals](https://github.com/rust-lang/rust/issues/105723): `c"string"` have been [stabilized in 1.77](https://github.com/rust-lang/edition-guide/pull/289), but that repository seems to not support them.

### Describe the solution you'd like

Implement c string literals

### Describe alternatives you've considered

Not having proper highlight

**Comment by amaanq** [comment]
They're already handled?
