### ISSUE TITLE
feature: Update version of `tree-sitter` crate to the latest one

### ISSUE THREAD

**Issue by Jujumba** [tree-sitter/tree-sitter-rust#217]
### Did you check the tree-sitter docs?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser

### Is your feature request related to a problem? Please describe.

The outdated version disallows proper use with latest `tree-sitter` version, also confuses a lot.

As the time of writing, the latest version of `tree-sitter` is `0.22.2` where as the crate uses `~0.20.10` version requirement.

### Describe the solution you'd like

Update the `Cargo.toml` file =)

Additionally, `tree-sitter` crate has broken semver semantics. `Parser::set_language` function's signature was changed, but the patch was submitted as a minor update. So more changes have to be made.

### Describe alternatives you've considered

None

**Comment by amaanq** [comment]
0.21.0 is now released on git(hub), crates, npm, and pypi
