### ISSUE TITLE
bug: slow textobject select queries

### ISSUE THREAD

**Issue by aclementev** [tree-sitter/tree-sitter-rust#225]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-rust

### Describe the bug

Opening a rust buffer with the `textobject.select.enable = true` option set is very slow.
The time difference when opening an empty `foo.rs` file is very noticeable (on my setup it's around ~700ms).

### Steps To Reproduce/Bad Parse Tree

1. Enable `textobject.select` treesitter plugin
2. Open any rust file, even an empty one: `nvim foo.rs`

### Expected Behavior/Parse Tree

I would expect the buffer to not take a noticeable amount of time to open (<300ms or something like that)

**Comment by ObserverOfTime** [comment]
https://github.com/nvim-treesitter/nvim-treesitter-textobjects

**Comment by aclementev** [comment]
I am familiar with the textobjects project, but I figured it would be related to this parser, since I use it with other multiple languages and this is the only one that shows this behavior
