### ISSUE TITLE
bug: Doesn't compile on bash

### ISSUE THREAD

**Issue by yuriv** [tree-sitter/tree-sitter-rust#233]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-rust

### Describe the bug

Doesn't compile on bash. Please, escape the `#` char in line 41 of the `Makefile`:

change
```bash
41: SONAME_MINOR := $(shell sed -n 's/#define LANGUAGE_VERSION //p' $(PARSER))
```
to
```bash
"41: SONAME_MINOR := $(shell sed -n 's/\#define LANGUAGE_VERSION //p' $(PARSER))"
```

### Steps To Reproduce/Bad Parse Tree

1. run make on bash

### Expected Behavior/Parse Tree

success

### Repro

```Rust
make
```

**Comment by ObserverOfTime** [comment]
Can't reproduce.

**Comment by amaanq** [comment]
Neither can I.

**Comment by yuriv** [comment]
after make is run i have got the message:
`Makefile:41: *** unterminated call to function 'shell': missing ')'.  Stop.`

my shell is
$ sh --version
GNU bash, version 4.4.20(1)-release (x86_64-redhat-linux-gnu)

 The problem is unescaped `#` char in line 41. Today i met with the same problem in the tree-sitter-c and tree-sitter-cpp parsers too.
