### ISSUE TITLE
feature: .text function to access value of nodes

### ISSUE THREAD

**Issue by reesericci** [tree-sitter/tree-sitter-rust#237]
### Did you check the tree-sitter docs?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser

### Is your feature request related to a problem? Please describe.

I'm looking to parse the value of identifiers in my language, but there is no convenient way to do this without splicing the source code.

### Describe the solution you'd like

A `.text` method like what is available in the JS and Python bindings

### Describe alternatives you've considered

None

**Comment by amaanq** [comment]
wrong repo, this is the parser, and such a method already exists - read the docs

**Comment by reesericci** [comment]
oops, my bad
