### ISSUE TITLE
Mark compatible with tree-sitter 0.22

### ISSUE THREAD

**Issue by joshka** [tree-sitter/tree-sitter-rust#247]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-rust

### Describe the bug

Dependabot wants to update tree-sitter in a repo I own, but this is not marked as compatible.

### Steps To Reproduce/Bad Parse Tree

a

### Expected Behavior/Parse Tree

a

**Comment by amaanq** [comment]
tree-sitter is no longer a dependency of any language crate.

**Comment by joshka** [comment]
https://github.com/ratatui/ratatui-website/pull/772 is a failing dependabot PR (it was a larger one, but I've manually resolved the other relevant updates)

**Comment by amaanq** [comment]
Oh I see, that's my mistake. I thought you were talking about the Rust crate here :sweat_smile: sorry about that

**Comment by joshka** [comment]
Ah got it - I see the where the confusion stems from now. My knowledge of the innards of tree-sitter are basically non-existent. it's like 20-30 lines of code in our website at https://github.com/ratatui/ratatui-website/blob/1b1f4100c3a3ee5ccfd1075e564fed49109bcbd0/src/plugins/remark-code-import.ts#L123-L157.  So much of this was my problem of miscommunicating the problem.

**Comment by amaanq** [comment]
Nice, that's really cool! I've gone ahead and updated the dependencies as well as released `0.23.2`
