### ISSUE TITLE
Any unicode character as identifiers (except emojis)

### ISSUE THREAD

**Issue by GrayJack** [tree-sitter/tree-sitter-rust#37]
Since this already supports greek characters, and that requires the feature gate
`#![feature(non_ascii_idents)]`
This package may as well support any unicode character as identifiers, as this feature gate allows to

**Comment by GrayJack** [comment]
I forgot to mention that emojis are not supported due many problems with that.
What I meant for this issue is to support all unicode characters that matches that feature gate

**Comment by narpfel** [comment]
I believe this is fixed? https://github.com/tree-sitter/tree-sitter-rust/commit/9d002eea75fe0c9dd2b3f1fa8b1d3c7f357ec2f8#diff-919ac210accac9ecc55a76d10a7590e3d85ca3f0e165b52d30f08faee486d0cbL1435-R1435
