### ISSUE TITLE
Doc strings parser

### ISSUE THREAD

**Issue by GrayJack** [tree-sitter/tree-sitter-rust#38]
It would be a nice enhancement if doc string comments would be parsed, to provide better highlights when documenting code

**Comment by Luni-4** [comment]
@GrayJack 

I think it would be better to differentiate `///` from `//` because they are assigned to the same token

**Comment by GrayJack** [comment]
I was talking about in doc comments be able to highlight the code inside the code block, adding a injection point

**Comment by Luni-4** [comment]
Oops, sorry, misunderstood the "parser" word used in this issue, I would open another one for my problem then :)

**Comment by GrayJack** [comment]
Well, I think we could think on both as the same problem, I have no problem with that

**Comment by Luni-4** [comment]
Yep, I agree :)

**Comment by augustocdias** [comment]
Maybe if injecting markdown in the `///` blocks since docs in rust are markdown.

**Comment by Chris00** [comment]
Duplicate of https://github.com/tree-sitter/tree-sitter-rust/issues/175.
