### ISSUE TITLE
Wrong AST due to greedy quantifier in raw_string_literal rule

### ISSUE THREAD

**Issue by p-e-w** [tree-sitter/tree-sitter-rust#4]
```
let a = r#""#; let b = r#""#;
```

parses as

```
(source_file (let_declaration (identifier) (raw_string_literal)))
```

which is wrong. The reason is that [the relevant patterns](https://github.com/tree-sitter/tree-sitter-rust/blob/master/grammar.js#L1116-L1118) employ greedy quantifiers and thus just skip over the second declaration.

Conceptually, the fix is simply to make the quantifiers lazy instead, but I'm not sure this would actually work since there is also a `repeat` (why?) and the quotes are not part of the regex itself.

tree-saw now has the ability to predict the AST that tree-sitter "should" produce, which allows it to automatically find issues like this one with no further input or guidance required.

**Comment by maxbrunsfeld** [comment]
Good catch. We should really handle raw strings with the external scanner, since they aren’t technically regular.
