### ISSUE TITLE
Raw identifiers are not supported

### ISSUE THREAD

**Issue by georgewfraser** [tree-sitter/tree-sitter-rust#68]
The following code is valid rust:

```rust
static r#message: &str = "Hello, world!";

fn main() {
  println!("{}", message);
}
```

But it is produces on error in tree-sitter-rust, for example when you enter it in the [playground](https://tree-sitter.github.io/tree-sitter/playground).

**Comment by GrayJack** [comment]
Raw identifier can happen in all places where normal identifier happens, right?

I think it's best that we define a raw_identifier and allow it where identifiers are allowed

**Comment by GrayJack** [comment]
@maxbrunsfeld is it important to known the distinction between raw identifiers and normal identifiers?

I think it is, cause it's invalid in loop labels, only normal identifiers are allowed.

**Comment by maxbrunsfeld** [comment]
Yeah, I think it should be a separate token. I agree with your suggestion to define `raw_identifier`, and add it as a choice in many of the places that `identifier` is currently allowed.

**Comment by GrayJack** [comment]
Would be a problem if I change the `field_identifier` and `type_identifier` to be a end node to be something like

```
(type_identifier
    (identifier))

(type_identifier
    (raw_identifier))
```
