### ISSUE TITLE
Glob imports from enums are incorrectly tagged

### ISSUE THREAD

**Issue by cbarrick** [tree-sitter/tree-sitter-rust#7]
When we define an enum, its name has `class="syntax--support syntax--type"`:

```rust
enum MyEnum {
    Int(i64),
    Float(f64),
}
```

When we use the enum, both in return position and in a function body, the name again has `class="syntax--support syntax--type"`:

```rust
fn foo() -> MyEnum {
    MyEnum::Int(42)
}
```

When we import a variant of an enum, the enum name yet again has `class="syntax--support syntax--type"`:

```rust
use super::MyEnum::Int;
```

**BUT** when we glob import from an enum, the enum name has `class="syntax--entity syntax--name syntax--class"`:

```rust
use super::MyEnum::*;
```

**Comment by maxbrunsfeld** [comment]
Thanks for the report! I missed that case.
