### ISSUE TITLE
Confusion between generic and shift operator

### ISSUE THREAD

**Issue by calixteman** [tree-sitter/tree-sitter-rust#73]
With the expression:
```rust
a as *mut A<<B as C>::D>
```
tree-sitter parses it like
```rust
(((a as *mut A) << B) as C) > ::D >
```
and the final `>` is erroneous.

I tryed to compile `let x = 1 as u32 << 1;` and I get:
```bash
error: `<` is interpreted as a start of generic arguments for `u32`, not a shift
 --> src/main.rs:2:22
  |
2 |     let x = 1 as u32 << 1;
  |             -------- ^^ - interpreted as generic arguments
  |             |        |
  |             |        not interpreted as shift
  |             help: try shifting the cast value: `(1 as u32)`
```
I wonder if we could do something similar in the grammar, I mean when we have a rule where a type is expected then a following `<` of `<<` must be interpret as a part of a generic and not as a bin operator.

**Comment by maxbrunsfeld** [comment]
Thanks for the report.

The problem is that we don't allow `as` in type argument lists. It is currently only allowed in paths like `<A as Iterator>::next`.

**Comment by calixteman** [comment]
@maxbrunsfeld I think `as` is ok in type argument lists thanks to `qualified_type`.
You can just add parenthesis around in `mut` argument.

**Comment by maxbrunsfeld** [comment]
Unless I'm missing something, the grammar currently does not allow `qualified_type` inside of `type_arguments`.

**Comment by calixteman** [comment]
With
```rust
a as *mut A<<B as C>::D>;
a as *mut A< <B as C>::D>;
```
I get:
```lisp
(source_file [0, 0] - [2, 0]
  (type_cast_expression [0, 0] - [1, 25]
    value: (binary_expression [0, 0] - [1, 1]
      left: (binary_expression [0, 0] - [0, 23]
        left: (type_cast_expression [0, 0] - [0, 19]
          value: (binary_expression [0, 0] - [0, 14]
            left: (type_cast_expression [0, 0] - [0, 11]
              value: (identifier [0, 0] - [0, 1])
              type: (pointer_type [0, 5] - [0, 11]
                (mutable_specifier [0, 6] - [0, 9])
                type: (type_identifier [0, 10] - [0, 11])))
            right: (identifier [0, 13] - [0, 14]))
          type: (type_identifier [0, 18] - [0, 19]))
        right: (scoped_identifier [0, 20] - [0, 23]
          name: (identifier [0, 22] - [0, 23])))
      (ERROR [0, 24] - [0, 25])
      right: (identifier [1, 0] - [1, 1]))
    type: (pointer_type [1, 5] - [1, 25]
      (mutable_specifier [1, 6] - [1, 9])
      type: (generic_type [1, 10] - [1, 25]
        type: (type_identifier [1, 10] - [1, 11])
        type_arguments: (type_arguments [1, 11] - [1, 25]
          (scoped_type_identifier [1, 13] - [1, 24]
            path: (bracketed_type [1, 13] - [1, 21]
              (qualified_type [1, 14] - [1, 20]
                type: (type_identifier [1, 14] - [1, 15])
                alias: (type_identifier [1, 19] - [1, 20])))
            name: (type_identifier [1, 23] - [1, 24])))))))
```

**Comment by maxbrunsfeld** [comment]
Oh, I'm sorry, you are right; I just misread the code there.

As you said, the problem is that the grammar thinks that both `<` and `<<` are valid after the `* mut A`. But really, `<<` should not be a valid token in this position. I will try to look into this a little bit more.

**Comment by maxbrunsfeld** [comment]
For now, my solution is that in any position where a type argument list is valid, a `<` should always be interpreted as the opening bracket for a type argument list (not a binary operator, or the beginning of a binary operator).

**Comment by calixteman** [comment]
Nice and thx
