### ISSUE TITLE
default is no more a function modifier so remove it

### ISSUE THREAD

**Issue by calixteman** [tree-sitter/tree-sitter-rust#74]
According to https://doc.rust-lang.org/reference/items/functions.html we could remove `default`.
Its presence in the grammar leads to error with for example:
```rust
pub struct A {
    a: default::C,
}
```
And nothing in:
https://doc.rust-lang.org/reference/keywords.html

@maxbrunsfeld are you ok to remove it ? if yes I'll do the PR.

**Comment by maxbrunsfeld** [comment]
That sounds good. I can't really remember the story behind the `default` modifier. If removing it allows us to parse code successfully that we couldn't parse before, I'm 👍 .

**Comment by amaanq** [comment]
The given example parses now
