### ISSUE TITLE
Grammar selector

### ISSUE THREAD

**Issue by ricvelozo** [tree-sitter/tree-sitter-rust#8]
Grammar selector not showing the Rust as option when in a plain text file file.

![captura de tela de 2018-12-09 23-08-47](https://user-images.githubusercontent.com/1834764/49705769-edd61100-fc07-11e8-9eb1-57b6bacedcea.png)

**Comment by Ben3eeE** [comment]
Thanks for taking the time to contribute!

This is actually a problem in Atom and not tree-sitter. There is an issue open for this already /cc: https://github.com/atom/atom/issues/17029. You may want to subscribe there for updates.
