### ISSUE TITLE
Bad parse of range expression with parenthesized right-side

### ISSUE THREAD

**Issue by joshuawarner32** [tree-sitter/tree-sitter-rust#86]
Hi! I just ran into a parse tree that looks incorrect to me. The following is parsed as a call expression, where the function is itself a range expression - rather than just being parsed as a range expression.

```rust
1..(1)
```

Expected:
```lisp
 (range_expression (integer_literal) (parenthesized_expression (integer_literal)))
```

Actual:
```lisp
(call_expression function: (range_expression (integer_literal)) arguments: (arguments (integer_literal)))
```

**Comment by maxbrunsfeld** [comment]
Thanks for the report.

**Comment by joshuawarner32** [comment]
I was looking into how to fix this - by first trying to understand how the current result falls out of the "_expression" declaration in grammar.json. It looks like call_expression/parenthesized_expression/range_expression all exist as part of the same precedence-driven parser. As a way of fixing this issue, it's clearly not valid to invert the precedences of the call expr and range exprs; that would cause all sorts of other problems. It seems to me this grammar quirk can't be modeled cleanly with precedence alone.

Do you have any tips on the right way to represent this in tree-sitter? Thanks!
