### ISSUE TITLE
Operators are not being highlighted

### ISSUE THREAD

**Issue by Avi-D-coder** [tree-sitter/tree-sitter-rust#87]
Other tree-sitter grammars parse `->`, `&&`, `+=`, etc. as an operator.
This grammar should be consistent  with the standard convention.

**Comment by GrayJack** [comment]
Pretty sure `&&` and `+=` are in the operator logic, they all show up in the `operator` field in the s-expr tree.

Now, `->` is not a operator by the official Rust syntax, and in this grammar it is not in a field, but I think it's possible to match a string in the queries.

**Comment by resolritter** [comment]
Maybe it's what's being reported in https://github.com/tree-sitter/tree-sitter-rust/issues/98?
