### ISSUE TITLE
Discriminate doc comments from single line comments

### ISSUE THREAD

**Issue by Luni-4** [tree-sitter/tree-sitter-rust#88]
It would be helpful to discriminate doc comments (///) from single line comments (//). Currently, they are assigned to the same token

**Comment by aryx** [comment]
Just curious, what is your use case? why do you need to discriminate them?

**Comment by bestouff** [comment]
I find it more ergonomic to see at a glance where doc comments are, and which parts of code have (or have no) doc comments.

**Comment by Luni-4** [comment]
> Just curious, what is your use case? why do you need to discriminate them?

It would be helpful to compute metrics that determine how much a code is documented in percentage

**Comment by koalp** [comment]
> Just curious, what is your use case? why do you need to discriminate them?

Another usecase mentioned in https://github.com/tree-sitter/tree-sitter-rust/pull/99#issuecomment-772129346 is to highlight doc comments as they are markdown. It would be especially useful for long documentation, for example in modules.
